### PR TITLE
refactor(src): change variable and function name to better reflect meaning

### LINKED ISSUE #5: `bool` is too generic of a variable name
See this [variable declaration](https://github.com/mozilla/fxa-password-strength-checker/blob/8e204254769d04ef35b3746cc5fe78ba0e470cbc/src/passwordcheck.js#L35)

`bool` is too generic and lacks meaning. Let's use a more descriptive name. If one variable is insufficient, use two.

### PR DESCRIPTION
**Pull request by TDA**
Fixes #5 #6 #7 
@shane-tomlinson 
@pdehaan

### CODE REVIEW

**Comment by vladikoff** [comment]
nit: commit message tag : `style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)`

`refactor` is probably better for this.

See https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines

**Comment by TDA** [comment]
@vladikoff done, r?

**Comment by shane-tomlinson** [comment]
@TDA - I mistakenly made my comments to this PR in #12, see that PR for my thoughts.

**Comment by TDA** [comment]
@shane-tomlinson I made changes to that PR, seeing as I would have had to rebase anyway :)

**Comment by TDA** [comment]
@shane-tomlinson Can we get this merged? I need rebasing on the other one.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Can we get this merged? I need rebasing on the other one.

The other is a super-set of this, right? If so, we can just close this and work with that.

**Comment by TDA** [comment]
@shane-tomlinson Sounds good. Closing.

**Pull request closed without merging**
